# Generated by Django 4.0.2 on 2022-02-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_the_leader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(upload_to=None),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to=None),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(upload_to=None),
        ),
    ]
