# Generated by Django 4.0.2 on 2022-03-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_the_leader', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_added',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
